### ISSUE TITLE
Multiline Not Working

### ISSUE THREAD

**Issue by arekstegienko-mohawkcollege** [potsky/PimpMyLog#106]
Hi, we wrote some custom regex for parsing Tomcat and custom formatted logs. Our logs contain multi-line messages and using the Debug Regex Tester (inc/test.php) we are able to get everything working correctly including the multi-line feature. However, when we use the exact same settings in the config.user.php file, multi-line support doesn't work in the actual application.

I have attached our config.user.php (as config.user.txt) file along with a sample log file (catalina.txt). Please feel free to check for yourself that using these settings things work correctly in the Debug Regex Tester, but not when running in the actual application. Is this currently a bug in the application or do we have a problem with our configuration?

Thanks,
Arek

P.S.  We're using version 1.7.10

[catalina.txt](https://github.com/potsky/PimpMyLog/files/251140/catalina.txt)
[config.user.txt](https://github.com/potsky/PimpMyLog/files/251141/config.user.txt)

**Comment by rhoerbe** [comment]
I run into a similar problem when creating a parser for shibboleth sp log files. Logparser seems to recognize the multilines, because it does not increase the error count. But the lines are not displayed.


[config.user.php.txt](https://github.com/potsky/PimpMyLog/files/295215/config.user.php.txt)
[shibd.log.txt](https://github.com/potsky/PimpMyLog/files/295217/shibd.log.txt)

**Comment by abhishekricky** [comment]
Hi,

I have logs in following format 

WEB,CREATE,MN123,NO,1500649872,21/07/17/20:07:09
WEB,CREATE,VIS12,NO,1500727060,22/07/17/18:07:97
WEB,CREATE,MC161BEC4PWB3A5NAJ,NO,1500995983,25/07/17/20:07:25
WEB,CREATE,COM01,YES,1501050633,26/07/17/12:07:49

I need to generate logs , tried various types of regex but not able can you guide me with correct regex
